Bug/df 2603 transfer info from job ads to npa anonymous
alv-ch/alv-portal pull request #856
Opened 2020-08-27 12:49 UTC by mdavidovski

- Check if job add is anonymous

- Format string value of it larger than a certain size

2020-08-27 13:43 UTC, seco-mgabor requested changes
There must be new unit tests in work-effort-form.mapper.spec, that cover the new code.

2020-08-27 13:43 UTC, seco-mgabor commented on alv-portal-ui/src/app/online-services/work-efforts/work-effort-form/work-effort-form.mapper.ts
These constants are defined in WorkEffortFormComponent already. 
I think they should be only in one place.

2020-08-28 08:52 UTC, mdavidovski commented
> There must be new unit tests in work-effort-form.mapper.spec, that cover the new code.

done

2020-08-28 15:09 UTC, seco-mgabor approved these changes

2020-08-31 07:28 UTC, c-linse approved these changes

2020-08-31 08:06 UTC, merged